// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotalmediaPOCApi.Models;

namespace TotalmediaPOCApi.Migrations
{
    [DbContext(typeof(TotalmediaPOCDbContext))]
    [Migration("20221215091357_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TotalmediaPOCApi.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("8fc99100-6c51-4b50-b640-abb96593cb6a"),
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = new Guid("0b1e9ce5-70a5-4d61-8a09-9e9dcfd80cec"),
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = new Guid("445ae582-533c-4a95-94de-60c4694dd220"),
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = new Guid("8e7ed540-a4a4-4f0a-80ba-dde9473b4f41"),
                            CountryName = "Spain"
                        });
                });

            modelBuilder.Entity("TotalmediaPOCApi.Models.CountryVATRate", b =>
                {
                    b.Property<Guid>("CountryVATRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CountryVATRateValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CountryVATRateId");

                    b.ToTable("CountryVATRates");

                    b.HasData(
                        new
                        {
                            CountryVATRateId = new Guid("5b86f9ef-1d81-4f75-a013-4ef19a23fa46"),
                            CountryId = new Guid("0b1e9ce5-70a5-4d61-8a09-9e9dcfd80cec"),
                            CountryVATRateValue = 5.5m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("06fff34f-0cc9-4a20-bad9-0a9111a347f2"),
                            CountryId = new Guid("0b1e9ce5-70a5-4d61-8a09-9e9dcfd80cec"),
                            CountryVATRateValue = 20m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("d7dffab9-1e36-4377-a076-01aaecd38a09"),
                            CountryId = new Guid("0b1e9ce5-70a5-4d61-8a09-9e9dcfd80cec"),
                            CountryVATRateValue = 10m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("bfdd0a03-40a4-42c8-87d5-7d03b15f9ad9"),
                            CountryId = new Guid("445ae582-533c-4a95-94de-60c4694dd220"),
                            CountryVATRateValue = 5m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("7a238b83-5238-4ce0-828c-b38c4f577765"),
                            CountryId = new Guid("445ae582-533c-4a95-94de-60c4694dd220"),
                            CountryVATRateValue = 20m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("c79d35ba-e75e-46dc-b7be-3dfed93b031a"),
                            CountryId = new Guid("8fc99100-6c51-4b50-b640-abb96593cb6a"),
                            CountryVATRateValue = 6m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("777cd10f-b105-4ae1-a2a6-2743d4c74331"),
                            CountryId = new Guid("8fc99100-6c51-4b50-b640-abb96593cb6a"),
                            CountryVATRateValue = 13m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("63c515d4-e4f9-40ec-a0a9-5d53221fbe7e"),
                            CountryId = new Guid("8fc99100-6c51-4b50-b640-abb96593cb6a"),
                            CountryVATRateValue = 23m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("31c2d3c0-8a16-490f-b242-c568f3f6928f"),
                            CountryId = new Guid("8e7ed540-a4a4-4f0a-80ba-dde9473b4f41"),
                            CountryVATRateValue = 21m
                        },
                        new
                        {
                            CountryVATRateId = new Guid("f7484de8-856e-45e7-86bf-40ad86ed470c"),
                            CountryId = new Guid("8e7ed540-a4a4-4f0a-80ba-dde9473b4f41"),
                            CountryVATRateValue = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
